In [23]:
# imports
import pandas as pd
import sqlalchemy
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func

In [24]:
# Create Engine for census data
path = "AllData.sqlite"
engine = create_engine(f"sqlite:///{path}")
conn = engine.connect()

In [27]:
senate = pd.read_csv('SPopulation1.csv')
attributes = pd.read_csv('CensusAttributesData.csv')
religion = pd.read_csv('ReligiousAffiliationByState.csv')

In [30]:
attributes.head()

,index,SUMLEV,REGION,DIVISION,STATE,NAME,SEX,ORIGIN,RACE,AGE,...,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,0,40,3,6,1,Alabama,0,0,1,0,...,37818,38678,37824,36812,37575,37698,37629,37526,36370,35594
1,1,40,3,6,1,Alabama,0,0,1,1,...,38036,37719,38597,37854,36968,37882,37732,37904,37641,36679
2,2,40,3,6,1,Alabama,0,0,1,2,...,39570,38202,37653,38528,37769,37123,38048,37975,38172,37904
3,3,40,3,6,1,Alabama,0,0,1,3,...,39805,39690,38113,37716,38605,37896,37266,38170,38197,38510
4,4,40,3,6,1,Alabama,0,0,1,4,...,39493,39872,39628,38122,37751,38625,37954,37322,38312,38476

In [29]:
senate.reset_index().to_sql("senate", con = conn, if_exists = 'replace')
attributes.reset_index().to_sql("attributes", con = conn, if_exists = 'replace')
religion.to_sql("religion", con = conn, if_exists = 'replace')

# why does it need to call from the root folder