In [9]:
import pandas as pd

# US Population - Sex, Race, (Age)

In [10]:
census_data_init = pd.read_csv("2020_decennial_census/DECENNIALPL2020.P2_data_with_overlays_2021-09-16T164642.csv")
census_data_init.iloc[1:].head()

,GEO_ID,NAME,P2_001N,P2_002N,P2_003N,P2_004N,P2_005N,P2_006N,P2_007N,P2_008N,...,P2_064N,P2_065N,P2_066N,P2_067N,P2_068N,P2_069N,P2_070N,P2_071N,P2_072N,P2_073N
1,0400000US01,Alabama,5024279,264047,4760232,4575614,3171351,1288159,23119,75918,...,4,108,51,44,9,0,2,2,2,2
2,0400000US02,Alaska,733391,49824,683567,611806,421758,20731,108838,43449,...,11,78,36,20,4,4,12,2,6,6
3,0400000US04,Arizona,7151502,2192253,4959249,4692409,3816547,317161,263930,248837,...,0,175,97,62,8,4,0,4,9,9
4,0400000US05,Arkansas,3011524,256847,2754677,2607520,2063550,449884,20549,51210,...,0,64,35,21,2,4,2,0,1,1
5,0400000US06,California,39538223,15579652,23958571,22330849,13714587,2119286,156085,5978795,...,15,1247,683,406,65,71,21,1,130,130

In [11]:
just_pop = census_data_init.iloc[1:].filter(items=['NAME', 'P2_001N'])
just_pop = just_pop.rename(columns={'NAME': 'state', 'P2_001N': 'population'})
just_pop.to_csv('census20pop.csv')
just_pop.head()

        state population
1     Alabama    5024279
2      Alaska     733391
3     Arizona    7151502
4    Arkansas    3011524
5  California   39538223

In [12]:
census_filtered = census_data_init.iloc[1:].filter(items=[
    'NAME', 
    'P2_001N', # total pop
    'P2_002N', # hispanic or latino
    # 3 is not-hispanic, 4 is one-race
    'P2_005N', # white
    'P2_006N', # black
    'P2_007N', # indigneous
    'P2_008N', # asian
    'P2_009N', # pacific islander
    'P2_010N', # other
    'P2_011N', # 2+ races
    ])

census_data = census_filtered.rename(columns={
    'NAME': 'state',
    'P2_001N': 'total',
    'P2_002N': 'hispanic',
    'P2_005N': 'white',
    'P2_006N': 'black',
    'P2_007N': 'indigenous',
    'P2_008N': 'asian',
    'P2_009N': 'hawaiian',
    'P2_010N': 'other',
    'P2_011N': 'multiple',
})

census_data = census_data.astype({
    'total': 'int', 
    'hispanic': 'int', 
    'white': 'int', 
    'black': 'int', 
    'indigenous': 'int', 
    'asian': 'int', 
    'hawaiian': 'int', 
    'other':'int', 
    'multiple':'int'})

start_table = census_data.sum()
start_table

state         AlabamaAlaskaArizonaArkansasCaliforniaColorado...
total                                                 334735155
hispanic                                               65329087
white                                                 191722195
black                                                  39944624
indigenous                                              2252011
asian                                                  19621465
hawaiian                                                 622109
other                                                   1692341
multiple                                               13551323
dtype: object

In [13]:
acs_2019_init = pd.read_csv('ACS_2019/ACSDP1Y2019.DP05_data_with_overlays_2021-08-06T114339.csv').iloc[1:]
acs_2019_init.head()

acs_sex_filtered = acs_2019_init.filter(items=[
    'DP05_0001E', # total pop
    'DP05_0002E', # men
    'DP05_0003E', # women
    ])

acs_sex_perc_filtered = acs_2019_init.filter(items=[
    'DP05_0002PE', # % men
    'DP05_0003PE', # % women
])

# ACS ALSO HAS AGE

acs_race_filtered = acs_2019_init.filter(items=[
    'DP05_0070E', # total pop
    'DP05_0071E', # hispanic or latino
    'DP05_0077E', # white
    'DP05_0078E', # black
    'DP05_0079E', # indigenous
    'DP05_0080E', # asian
    'DP05_0081E', # Hawaiian
    'DP05_0082E', # other
    'DP05_0083E', # multiple races
])
acs_race_perc_filtered = acs_2019_init.filter(items=[
    'DP05_0071PE', # hispanic or latino
    'DP05_0077PE', # white
    'DP05_0078PE', # black
    'DP05_0079PE', # indigenous
    'DP05_0080PE', # asian
    'DP05_0081PE', # Hawaiian
    'DP05_0082PE', # other
    'DP05_0083PE', # multiple races
])
# note: just change to PE for percent

In [14]:
acs_sex = acs_sex_filtered.rename(columns={
    'DP05_0001E': 'total', # total pop
    'DP05_0002E': 'num_men', # men
    'DP05_0003E': 'num_women', # women
})

acs_sex_perc = acs_sex_perc_filtered.rename(columns={
    'DP05_0002PE': 'perc_men', # % men
    'DP05_0003PE': 'perc_women', # % women
})

acs_race = acs_race_filtered.rename(columns={
    'DP05_0070E': 'total', # total pop
    'DP05_0071E': 'hispanic', # hispanic or latino
    'DP05_0077E': 'white', # white
    'DP05_0078E': 'black', # black
    'DP05_0079E': 'indigenous', # indigenous
    'DP05_0080E': 'asian', # asian
    'DP05_0081E': 'hawaiian', # Hawaiian
    'DP05_0082E': 'other', # other
    'DP05_0083E': 'multiple', # multiple races
})

acs_race_perc = acs_race_perc_filtered.rename(columns={
    'DP05_0071PE': 'hispanic', # hispanic or latino
    'DP05_0077PE': 'white', # white
    'DP05_0078PE': 'black', # black
    'DP05_0079PE': 'indigenous', # indigenous
    'DP05_0080PE': 'asian', # asian
    'DP05_0081PE': 'hawaiian', # Hawaiian
    'DP05_0082PE': 'other', # other
    'DP05_0083PE': 'multiple', # multiple races
})

In [15]:
comp = pd.DataFrame(start_table).drop("state").join(acs_race.transpose())

comp['perc census'] = comp[0] / 3347351.55
comp[1] = comp[1].astype(int)
comp['perc acs'] = comp[1] / 3282395.23
comp.rename(columns={0: 'census2020', 1: 'acs2019'}, inplace=True)
comp

#SIGH. Conclusion: a couple races have shifted by a couple percentage points enough that it's worth using the 2020 data

           census2020    acs2019 perc census    perc acs
total       334735155  328239523       100.0  100.000000
hispanic     65329087   60481746    19.51665   18.426101
white       191722195  196789401   57.275787   59.952988
black        39944624   40596040   11.933203   12.367810
indigenous    2252011    2236348    0.672774    0.681316
asian        19621465   18427914    5.861788    5.614167
hawaiian       622109     565473    0.185851    0.172275
other         1692341     839270    0.505576    0.255688
multiple     13551323    8303331    4.048372    2.529656

In [21]:
final_sex_perc = acs_sex_perc.iloc[0].astype(float)
final_race_perc = comp['perc census'].drop("total")

sex_json = final_sex_perc.to_json(open("../senate-react/src/data0/sex0.json", 'w'))
race_json = final_race_perc.to_json(open("../senate-react/src/data0/race0.json", 'w'))

In [22]:
final_sex_perc.sum()

100.0

# Religion
**TODO**